name = "exchange-api"
main = "src/index.ts"
compatibility_date = "2025-11-04"

# 开启变量保留，部署时绝对不清空 Dashboard 里的 API_KEY 等 Secret
keep_vars = true

[triggers]
crons = ["0 */1 * * *"]

[vars]
RATE_LIMIT = "200"